version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/mi-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/mi-front"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"