apiVersion: v1
kind: Service
metadata:
  name: mi-front
  namespace: docker-testing
  labels:
    app: mi-front
spec:
  type: LoadBalancer
  selector:
    app: mi-front
  ports:
    - name: http
      port: 80
      targetPort: 3001
