apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-front
  namespace: docker-testing
  labels:
    app: mi-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-front
  template:
    metadata:
      labels:
        app: mi-front
    spec:
      containers:
        - name: mi-front
          image: ${ECR_FRONTEND_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
              name: http
          envFrom:
            - configMapRef:
                name: frontend-config
          readinessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
